export const NSE_STOCKS = [
  // ── NIFTY 50 Core ──────────────────────────────────────────────────
  { symbol: "RELIANCE", name: "Reliance Industries Ltd." },
  { symbol: "TCS", name: "Tata Consultancy Services Ltd." },
  { symbol: "HDFCBANK", name: "HDFC Bank Ltd." },
  { symbol: "ICICIBANK", name: "ICICI Bank Ltd." },
  { symbol: "INFY", name: "Infosys Ltd." },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever Ltd." },
  { symbol: "SBIN", name: "State Bank of India" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel Ltd." },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank Ltd." },
  { symbol: "LT", name: "Larsen & Toubro Ltd." },
  { symbol: "ITC", name: "ITC Ltd." },
  { symbol: "AXISBANK", name: "Axis Bank Ltd." },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical Industries Ltd." },
  { symbol: "BAJFINANCE", name: "Bajaj Finance Ltd." },
  { symbol: "MARUTI", name: "Maruti Suzuki India Ltd." },
  { symbol: "TITAN", name: "Titan Company Ltd." },
  { symbol: "HCLTECH", name: "HCL Technologies Ltd." },
  { symbol: "TATAMOTORS", name: "Tata Motors Ltd." },
  { symbol: "WIPRO", name: "Wipro Ltd." },
  { symbol: "NTPC", name: "NTPC Ltd." },
  { symbol: "ONGC", name: "Oil & Natural Gas Corporation Ltd." },
  { symbol: "POWERGRID", name: "Power Grid Corporation of India Ltd." },
  { symbol: "COALINDIA", name: "Coal India Ltd." },
  { symbol: "ADANIENT", name: "Adani Enterprises Ltd." },
  { symbol: "ADANIPORTS", name: "Adani Ports & Special Economic Zone" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement Ltd." },
  { symbol: "ASIANPAINT", name: "Asian Paints Ltd." },
  { symbol: "NESTLEIND", name: "Nestle India Ltd." },
  { symbol: "JSWSTEEL", name: "JSW Steel Ltd." },
  { symbol: "TATASTEEL", name: "Tata Steel Ltd." },
  { symbol: "M&M", name: "Mahindra & Mahindra Ltd." },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv Ltd." },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto Ltd." },
  { symbol: "INDUSINDBK", name: "IndusInd Bank Ltd." },
  { symbol: "DRREDDY", name: "Dr. Reddy's Laboratories Ltd." },
  { symbol: "CIPLA", name: "Cipla Ltd." },
  { symbol: "DIVISLAB", name: "Divi's Laboratories Ltd." },
  { symbol: "BRITANNIA", name: "Britannia Industries Ltd." },
  { symbol: "TECHM", name: "Tech Mahindra Ltd." },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp Ltd." },
  { symbol: "BPCL", name: "Bharat Petroleum Corporation Ltd." },
  { symbol: "EICHERMOT", name: "Eicher Motors Ltd." },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals Enterprise Ltd." },
  { symbol: "GRASIM", name: "Grasim Industries Ltd." },
  { symbol: "TATACONSUM", name: "Tata Consumer Products Ltd." },
  { symbol: "HINDALCO", name: "Hindalco Industries Ltd." },
  { symbol: "SBILIFE", name: "SBI Life Insurance Company Ltd." },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance Company Ltd." },

  // ── NIFTY Next 50 & Mid-Cap Stars ──────────────────────────────────
  { symbol: "HAL", name: "Hindustan Aeronautics Ltd." },
  { symbol: "BEL", name: "Bharat Electronics Ltd." },
  { symbol: "BHEL", name: "Bharat Heavy Electricals Ltd." },
  { symbol: "COCHINSHIP", name: "Cochin Shipyard Ltd." },
  { symbol: "DLF", name: "DLF Ltd." },
  { symbol: "GODREJPROP", name: "Godrej Properties Ltd." },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty Ltd." },
  { symbol: "PRESTIGE", name: "Prestige Estates Projects Ltd." },
  { symbol: "PHOENIXLTD", name: "Phoenix Mills Ltd." },
  { symbol: "BRIGADE", name: "Brigade Enterprises Ltd." },
  { symbol: "ZOMATO", name: "Zomato Ltd." },
  { symbol: "TRENT", name: "Trent Ltd." },
  { symbol: "DMART", name: "Avenue Supermarts Ltd." },
  { symbol: "ADANIGREEN", name: "Adani Green Energy Ltd." },
  { symbol: "ADANIPOWER", name: "Adani Power Ltd." },
  { symbol: "TATAPOWER", name: "Tata Power Company Ltd." },
  { symbol: "NHPC", name: "NHPC Ltd." },
  { symbol: "SJVN", name: "SJVN Ltd." },
  { symbol: "IRFC", name: "Indian Railway Finance Corporation" },
  { symbol: "RECLTD", name: "REC Ltd." },
  { symbol: "PFC", name: "Power Finance Corporation Ltd." },
  { symbol: "VEDL", name: "Vedanta Ltd." },
  { symbol: "HINDZINC", name: "Hindustan Zinc Ltd." },
  { symbol: "NATIONALUM", name: "National Aluminium Company Ltd." },
  { symbol: "SAIL", name: "Steel Authority of India Ltd." },
  { symbol: "NMDC", name: "NMDC Ltd." },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power Ltd." },
  { symbol: "ABB", name: "ABB India Ltd." },
  { symbol: "SIEMENS", name: "Siemens Ltd." },
  { symbol: "HAVELLS", name: "Havells India Ltd." },
  { symbol: "CUMMINSIND", name: "Cummins India Ltd." },
  { symbol: "LTIM", name: "LTIMindtree Ltd." },
  { symbol: "MPHASIS", name: "Mphasis Ltd." },
  { symbol: "COFORGE", name: "Coforge Ltd." },
  { symbol: "PERSISTENT", name: "Persistent Systems Ltd." },
  { symbol: "TATAELXSI", name: "Tata Elxsi Ltd." },
  { symbol: "VBL", name: "Varun Beverages Ltd." },
  { symbol: "COLPAL", name: "Colgate-Palmolive (India) Ltd." },
  { symbol: "DABUR", name: "Dabur India Ltd." },
  { symbol: "MARICO", name: "Marico Ltd." },
  { symbol: "GODREJCP", name: "Godrej Consumer Products Ltd." },
  { symbol: "LUPIN", name: "Lupin Ltd." },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma Ltd." },
  { symbol: "BIOCON", name: "Biocon Ltd." },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals Ltd." },
  { symbol: "ALKEM", name: "Alkem Laboratories Ltd." },
  { symbol: "ZYDUSLIFE", name: "Zydus Lifesciences Ltd." },
  { symbol: "IPCALAB", name: "IPCA Laboratories Ltd." },
  { symbol: "GLENMARK", name: "Glenmark Pharmaceuticals Ltd." },
  { symbol: "PNB", name: "Punjab National Bank" },
  { symbol: "BANKBARODA", name: "Bank of Baroda" },
  { symbol: "CANBK", name: "Canara Bank" },
  { symbol: "IOB", name: "Indian Overseas Bank" },
  { symbol: "INDIANB", name: "Indian Bank" },
  { symbol: "FEDERALBNK", name: "Federal Bank Ltd." },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank Ltd." },
  { symbol: "BANDHANBNK", name: "Bandhan Bank Ltd." },
  { symbol: "AUBANK", name: "AU Small Finance Bank Ltd." },
  { symbol: "IOC", name: "Indian Oil Corporation Ltd." },
  { symbol: "GAIL", name: "GAIL (India) Ltd." },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life Insurance" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment & Finance" },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance Ltd." },
  { symbol: "MANAPPURAM", name: "Manappuram Finance Ltd." },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance Ltd." },
  { symbol: "SHRIRAMFIN", name: "Shriram Finance Ltd." },
  { symbol: "TVSMOTOR", name: "TVS Motor Company Ltd." },
  { symbol: "ASHOKLEY", name: "Ashok Leyland Ltd." },
  { symbol: "MOTHERSON", name: "Motherson Sumi Wiring Ltd." },
  { symbol: "BHARATFORG", name: "Bharat Forge Ltd." },
  { symbol: "MRF", name: "MRF Ltd." },
  { symbol: "APOLLOTYRE", name: "Apollo Tyres Ltd." },
  { symbol: "BALKRISIND", name: "Balkrishna Industries Ltd." },
  { symbol: "POLYCAB", name: "Polycab India Ltd." },
  { symbol: "KEI", name: "KEI Industries Ltd." },
  { symbol: "DIXON", name: "Dixon Technologies Ltd." },
  { symbol: "KAYNES", name: "Kaynes Technology India Ltd." },
  { symbol: "VOLTAS", name: "Voltas Ltd." },
  { symbol: "CROMPTON", name: "Crompton Greaves Consumer Electricals" },
  { symbol: "BATAINDIA", name: "Bata India Ltd." },
  { symbol: "PAGEIND", name: "Page Industries Ltd." },
  { symbol: "PIDILITIND", name: "Pidilite Industries Ltd." },
  { symbol: "SRF", name: "SRF Ltd." },
  { symbol: "PIIND", name: "PI Industries Ltd." },
  { symbol: "DEEPAKNTR", name: "Deepak Nitrite Ltd." },
  { symbol: "NAVINFLUOR", name: "Navin Fluorine International Ltd." },
  { symbol: "ATUL", name: "Atul Ltd." },
  { symbol: "CLEAN", name: "Clean Science & Technology Ltd." },
  { symbol: "UPL", name: "UPL Ltd." },
  { symbol: "SHREECEM", name: "Shree Cement Ltd." },
  { symbol: "AMBUJACEM", name: "Ambuja Cements Ltd." },
  { symbol: "ACC", name: "ACC Ltd." },
  { symbol: "RAMCOCEM", name: "Ramco Cements Ltd." },
  { symbol: "DALBHARAT", name: "Dalmia Bharat Ltd." },
  { symbol: "JKCEMENT", name: "JK Cement Ltd." },
  { symbol: "INDIGO", name: "InterGlobe Aviation Ltd." },
  { symbol: "CONCOR", name: "Container Corporation of India Ltd." },
  { symbol: "DELHIVERY", name: "Delhivery Ltd." },
  { symbol: "MAXHEALTH", name: "Max Healthcare Institute Ltd." },
  { symbol: "FORTIS", name: "Fortis Healthcare Ltd." },
  { symbol: "LALPATHLAB", name: "Dr Lal PathLabs Ltd." },
  { symbol: "METROPOLIS", name: "Metropolis Healthcare Ltd." },
  { symbol: "JIOFIN", name: "Jio Financial Services Ltd." },
  { symbol: "LICI", name: "Life Insurance Corporation of India" },
  { symbol: "NAUKRI", name: "Info Edge (India) Ltd." },
  { symbol: "PAYTM", name: "One97 Communications Ltd." },
  { symbol: "YESBANK", name: "Yes Bank Ltd." },
  { symbol: "IDEA", name: "Vodafone Idea Ltd." },
  { symbol: "IRCTC", name: "IRCTC Ltd." },
  { symbol: "RVNL", name: "Rail Vikas Nigam Ltd." },
  { symbol: "SUZLON", name: "Suzlon Energy Ltd." },
  { symbol: "TATACOMM", name: "Tata Communications Ltd." },
  { symbol: "INDUSTOWER", name: "Indus Towers Ltd." },
  { symbol: "BOSCHLTD", name: "Bosch Ltd." },
  { symbol: "SUNTV", name: "Sun TV Network Ltd." },
  { symbol: "ZEEL", name: "Zee Entertainment Enterprises Ltd." },
  { symbol: "PVR", name: "PVR INOX Ltd." },
  { symbol: "EXIDEIND", name: "Exide Industries Ltd." },
  { symbol: "AMARARAJA", name: "Amara Raja Energy & Mobility Ltd." },
  { symbol: "CHAMBAL", name: "Chambal Fertilisers & Chemicals Ltd." },
  { symbol: "COROMANDEL", name: "Coromandel International Ltd." },
  { symbol: "INDHOTEL", name: "Indian Hotels Company Ltd." },
  { symbol: "STARHEALTH", name: "Star Health & Allied Insurance" },
  { symbol: "NYKAA", name: "FSN E-Commerce Ventures Ltd." },
  { symbol: "SOLARINDS", name: "Solar Industries India Ltd." },
  { symbol: "DATAPATTNS", name: "Data Patterns (India) Ltd." },
  { symbol: "MAZAGON", name: "Mazagon Dock Shipbuilders Ltd." },
  { symbol: "GRSE", name: "Garden Reach Shipbuilders Ltd." },
];
