export const NSE_STOCKS = [
  { symbol: "RELIANCE", name: "Reliance Industries Ltd." },
  { symbol: "TCS", name: "Tata Consultancy Services Ltd." },
  { symbol: "HDFCBANK", name: "HDFC Bank Ltd." },
  { symbol: "ICICIBANK", name: "ICICI Bank Ltd." },
  { symbol: "BHARTIARTL", name: "Bharti Airtel Ltd." },
  { symbol: "SBIN", name: "State Bank of India" },
  { symbol: "INFY", name: "Infosys Ltd." },
  { symbol: "LICI", name: "Life Insurance Corporation of India" },
  { symbol: "ITC", name: "ITC Ltd." },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever Ltd." },
  { symbol: "LT", name: "Larsen & Toubro Ltd." },
  { symbol: "BAJFINANCE", name: "Bajaj Finance Ltd." },
  { symbol: "HCLTECH", name: "HCL Technologies Ltd." },
  { symbol: "MARUTI", name: "Maruti Suzuki India Ltd." },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical Industries Ltd." },
  { symbol: "ADANIENT", name: "Adani Enterprises Ltd." },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank Ltd." },
  { symbol: "TITAN", name: "Titan Company Ltd." },
  { symbol: "ONGC", name: "Oil & Natural Gas Corporation Ltd." },
  { symbol: "TATAMOTORS", name: "Tata Motors Ltd." },
  { symbol: "NTPC", name: "NTPC Ltd." },
  { symbol: "AXISBANK", name: "Axis Bank Ltd." },
  { symbol: "DMART", name: "Avenue Supermarts Ltd." },
  { symbol: "ADANIGREEN", name: "Adani Green Energy Ltd." },
  { symbol: "ADANIPORTS", name: "Adani Ports & Special Economic Zone" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement Ltd." },
  { symbol: "ASIANPAINT", name: "Asian Paints Ltd." },
  { symbol: "COALINDIA", name: "Coal India Ltd." },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv Ltd." },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto Ltd." },
  { symbol: "POWERGRID", name: "Power Grid Corporation of India Ltd." },
  { symbol: "NESTLEIND", name: "Nestle India Ltd." },
  { symbol: "WIPRO", name: "Wipro Ltd." },
  { symbol: "M&M", name: "Mahindra & Mahindra Ltd." },
  { symbol: "IOC", name: "Indian Oil Corporation Ltd." },
  { symbol: "JIOFIN", name: "Jio Financial Services Ltd." },
  { symbol: "HAL", name: "Hindustan Aeronautics Ltd." },
  { symbol: "DLF", name: "DLF Ltd." },
  { symbol: "ADANIPOWER", name: "Adani Power Ltd." },
  { symbol: "JSWSTEEL", name: "JSW Steel Ltd." },
  { symbol: "TATASTEEL", name: "Tata Steel Ltd." },
  { symbol: "SIEMENS", name: "Siemens Ltd." },
  { symbol: "IRFC", name: "Indian Railway Finance Corporation" },
  { symbol: "VBL", name: "Varun Beverages Ltd." },
  { symbol: "ZOMATO", name: "Zomato Ltd." },
  { symbol: "PIDILITIND", name: "Pidilite Industries Ltd." },
  { symbol: "GRASIM", name: "Grasim Industries Ltd." },
  { symbol: "SBILIFE", name: "SBI Life Insurance Company Ltd." },
  { symbol: "BEL", name: "Bharat Electronics Ltd." },
  { symbol: "LTIM", name: "LTIMindtree Ltd." },
  { symbol: "TRENT", name: "Trent Ltd." },
  { symbol: "PNB", name: "Punjab National Bank" },
  { symbol: "INDIGO", name: "InterGlobe Aviation Ltd." },
  { symbol: "BANKBARODA", name: "Bank of Baroda" },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance Company Ltd." },
  { symbol: "ABB", name: "ABB India Ltd." },
  { symbol: "BPCL", name: "Bharat Petroleum Corporation Ltd." },
  { symbol: "PFC", name: "Power Finance Corporation Ltd." },
  { symbol: "GODREJCP", name: "Godrej Consumer Products Ltd." },
  { symbol: "TATAPOWER", name: "Tata Power Company Ltd." },
  { symbol: "HINDALCO", name: "Hindalco Industries Ltd." },
  { symbol: "RECX", name: "REC Ltd." },
  { symbol: "AMBUJACEM", name: "Ambuja Cements Ltd." },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment & Finance" },
  { symbol: "HINDZINC", name: "Hindustan Zinc Ltd." },
  { symbol: "TVSMOTOR", name: "TVS Motor Company Ltd." },
  { symbol: "EICHERMOT", name: "Eicher Motors Ltd." },
  { symbol: "DIVISLAB", name: "Divi's Laboratories Ltd." },
  { symbol: "DRREDDY", name: "Dr. Reddy's Laboratories Ltd." },
  { symbol: "CIPLA", name: "Cipla Ltd." },
  { symbol: "TATACONSUM", name: "Tata Consumer Products Ltd." },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals Enterprise Ltd." },
  { symbol: "INDUSINDBK", name: "IndusInd Bank Ltd." },
  { symbol: "BRITANNIA", name: "Britannia Industries Ltd." },
  { symbol: "TECHM", name: "Tech Mahindra Ltd." },
  { symbol: "SHREECEM", name: "Shree Cement Ltd." },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp Ltd." },
  { symbol: "LUPIN", name: "Lupin Ltd." },
  { symbol: "GAIL", name: "GAIL (India) Ltd." },
  { symbol: "ZYDUSLIFE", name: "Zydus Lifesciences Ltd." },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals Ltd." },
  { symbol: "BOSCHLTD", name: "Bosch Ltd." },
  { symbol: "UPL", name: "UPL Ltd." },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life Insurance" },
  { symbol: "MARICO", name: "Marico Ltd." },
  { symbol: "MRF", name: "MRF Ltd." },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance Ltd." },
  { symbol: "YESBANK", name: "Yes Bank Ltd." }
];
